SRCDIR = ../src
SED:=$(shell command -v gsed || which sed)

all: doxygen

##############################
# Doxygen HTML documentation #
##############################

# create Doxygen documentation
doxygen:
	doxygen
	echo -e "\n\033[0;41mWarning: Unworking functionnality for now, debug needed before using Doxygen.\033[0;0m"
