#!/bin/bash
echo "Generating the header-only file .."

HOME=`git rev-parse --show-toplevel`

# Remove all trailing whitespaces
#cd ${HOME}
#for filename in `find -follow | grep -E '\.(cpp|h|hpp)$' | grep -v './test/third-party' | grep -v './build'`; do
#	sed -i 's/[ \t]*$//' ${filename}
#done

LOCATION=${HOME}/single_include
mkdir -p "$LOCATION"
FILE="$LOCATION/graph.hpp"

cat > "$FILE" << EOF
/*
 *    ╔═╗╦═╗╔═╗╔═╗╦ ╦  C++ Graph library
 *    ║ ╦╠╦╝╠═╣╠═╝╠═╣  Version 1.0.0
 *    ╚═╝╩╚═╩ ╩╩  ╩ ╩  https://github.com/Terae/Structure
 *
 *
 * Single header-file generated by $USER on $(date +%F)
 *
 *
 * Licensed under the MIT License <https://opensource.org/licenses/MIT>.
 * Copyright (c) 2017 Benjamin BIGEY
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to wholm the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 *
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

EOF

# Copying Graph.h, Graph.cpp and Node.cpp into graph.hpp
sed -e '/#include "Graph.cpp"/ {' -e "r ${HOME}/src/Node.cpp" -e "r ${HOME}/src/Graph.cpp" -e 'd' -e '}' ${HOME}/src/Graph.h >> "$FILE"
# Copying Node.h into graph.hpp
sed -i -e '/#include "Node.h"/ {' -e "r ${HOME}/src/Node.h" -e 'd' -e '}' "$FILE"
sed -i '/#include "Node.cpp"/,+2d' "$FILE"
sed -i 's/#include <Node.h>//' "$FILE"
sed -i 's/#include <Graph.h>//' "$FILE"
# Copying exception.hpp into graph.hpp
sed -i -e '/#include "detail.hpp"/ {' -e "r ${HOME}/src/detail.hpp" -e 'd' -e '}' "$FILE"
# Modifying #ifndef/#define values
sed -i 's/ROOT_GRAPH_H/ROOT_GRAPH_FINAL_H/' "$FILE"
sed -i '/ROOT_NODE_H/d' "$FILE"
sed -i '/ROOT_DETAIL_H/d' "$FILE"
# Remove comments
sed -i 's/\/\/\/.*//' "$FILE"
# Remove trailing whitespaces
sed -i 's/[ \t]*$//' "$FILE"
# Remove unnecessary EOF
sed -i '/^$/N;/\n$/D' "$FILE"
